use worker_a::error::Result;

#[tokio::main]
async fn main() -> Result<()> {

    Ok(())
}